### PR TITLE
Update AWS resource specification

### PR DESCRIPTION
**Pull request by ans0600**
The new parameters added in this commit (https://github.com/stevenjack/cfndsl/pull/312) seems not working without the corresponding record in resource_specification.json.

Update the resource_specification.json using command cfndsl -u

### CODE REVIEW

**Comment by ans0600** [comment]
@AnominousSign I find your commit is not working without the following in resource_specification.json

```
"TreatMissingData": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarms-treatmissingdata",
          "PrimitiveType": "String",
          "Required": false,
          "UpdateType": "Mutable"
        },
```

**Comment by ans0600** [comment]
@stevenjack what is the purpose of resource_specification.json ? Should we update this every time when new attribute being added to types.yaml ?

**Comment by gergnz** [comment]
Hi @ans0600,

The file is specified here:
https://github.com/stevenjack/cfndsl/blob/master/lib/cfndsl/globals.rb#L21-L25

As you can see it's stored in your home directory outside of the code base.  Their is a version shipped to _bootstrap_ but that's about it.

We have done some overrides:
https://github.com/stevenjack/cfndsl/blob/master/lib/cfndsl/patches.rb as the spec wasn't correct as per the documentation.

Please double check if the spec includes what you need and/or is as per the documentation or if we need to provide an override.

if the spec is missing something, we can put in an override, but please also raise a case with AWS support.

**Comment by ans0600** [comment]
@gergnz Thanks for your reply. To be honest it is the first time I realise there is a -u flag and the existence of resource_specification.json

After reading your comment, it seems like it is better to generate this file prior to generate any template? I cannot find anything mentioning about it in Readme. I reckon most of people does not know this until they start to use attributes not included with the "bootstrap specification".

**Pull request closed without merging**
