### PR TITLE
enable deep merge as the default for yaml

### LINKED ISSUE #327: Please add support for multiple input files with deep merge
It would be nice if we could specify multiple input files so that we can have a common set of input for any cfndsl call and then different input files for various components.

I envision something like this:
```
cfndsl ----yaml common.yml --yaml app_specific.yaml my_cfndsl_template.rb
```

The contents should be merged, with subsequent files overwriting any duplicate keys (with a deep yaml merge) in order of input files specified on the CLI.

### PR DESCRIPTION
**Pull request by gergnz**
Resolves #327

### CODE REVIEW

**Comment by kornypoet** [comment]
Looks good @gergnz. Can we write some tests for the two behaviors (deep_merge vs not)? This is decently user-affecting, and there should be expectations around that.

**Comment by gergnz** [comment]
Given this comment: https://github.com/stevenjack/cfndsl/pull/326#issuecomment-308580835, would you still like to include the code, or should we just require the deep_merge gem?

Yes, I'll get on and write some tests.

**Comment by kornypoet** [comment]
I would like to stick with the "no external dependencies" for now. But if this comes up again, it might be time to decide a new strategy.

**Comment by kornypoet** [comment]
👍

**Comment by kornypoet** [comment]
@gergnz Feel free to merge this and release

**Comment by eric-tucker** [comment]
Yay!  

Is this pushed up to the gem repository?

**Comment by gergnz** [comment]
@eric-tucker, yes this should be v0.15

**Comment by eric-tucker** [comment]
Thanks so much @gergnz .  You (and the cfndsl team) rock.  Your turn around on issues/features is amazing.

**Comment by khushal08** [comment]
Sounds very interesting. Keen to try it out 👍🏽

**Pull request merged**
