### PR TITLE
Exparams class methods

### PR DESCRIPTION
**Pull request by kornypoet**
Rework this behavior appropriately. Now includes defaults.

### CODE REVIEW

**Comment by kornypoet** [comment]
@stevenjack Have you had a chance to review this yet?

**Comment by kornypoet** [comment]
@stevenjack bump

**Comment by stevenjack** [comment]
Sorry @kornypoet I've been in Costa Rica for three weeks but back in a few days do will have a proper look then!

**Comment by stevenjack** [comment]
@kornypoet not too sure about the `current` method and it either returning what's been set or calling `refresh!` to create a new instance - all seems to be a bit of a smell of something not quite right here..

Could you just run it by me why we need to `refresh!` the module each time?

**Comment by kornypoet** [comment]
The ExternalParams class can't set a static value for the configuration it receives. It needs to remain the same from template to template. If you generate more than one template at a time, the configuration should be the same, unaltered, but not the same object id.

The need for the indirection is because the parameters need to be accessible from all levels of the template. It was getting very messy trying to create scoped access methods that all referenced the same object, for all the potential nested classes.

The `@current || refresh!` is just a ruby shorthand. I prefer things terse, but the logic is as follows:

* Some object will access the `ExternalParams.current` method. If no defaults have been set, nor any configuration loaded, an empty hash should at least be returned to meet expected behaviors.
* We need a way to "unset" the current parameters since it is a class-level attribute; otherwise it might persist between invocations within the same Ruby VM, or template generations.
* If defaults are set for us, we need a way to keep re-populating the base hash.
* The logic of how to manage the above should be kept conceptually with the params class itself, with minimal outside api exposure to prevent code bleed.

We can change the look and feel of the class a bit if you'd prefer, but I'm happy with the behavior and implementation. Is there something in particular that is "bad" about this approach?

**Comment by kornypoet** [comment]
So what do we think?

**Comment by kornypoet** [comment]
Bump @stevenjack

**Comment by stevenjack** [comment]
@kornypoet sorry I've not been able to get to this. I don't think my concerns are enough to block this, let's get it merged.

**Pull request merged**
