### PR TITLE
External parameters

### PR DESCRIPTION
**Pull request by kornypoet**
First pass at `ExternalParameters` class:

* Flag for disabling binding; on by default with a deprecation warning
* Current `ExternalParameters` class has minimal hash methods; more can be added later.
* Tested, RuboCop'ed

### CODE REVIEW

**Comment by stevenjack** [comment]
@kornypoet LGTM, could you add a small section in the README about how to use it? I'm looking at updating the readme once I've got through the backlog of PR's and issues that have been hanging around.

**Comment by stevenjack** [comment]
@kornypoet Could you rebase this against master as the rubocop fixes have now been merged and have a look at adding the small snippet into the README?

**Comment by kornypoet** [comment]
Yep

**Comment by stevenjack** [comment]
@kornypoet Also you might have to create a new PR as I'm not sure if you can change the target it compares against once the PR has been created as this ones currently pointing at `johnf_rubocop`.

**Comment by kornypoet** [comment]
Remix: https://github.com/stevenjack/cfndsl/pull/179

**Pull request closed without merging**
