### PR TITLE
Support for FnSub

### PR DESCRIPTION
**Pull request by cmaxwellau**
For #241. No rubocop tests as yet.

### CODE REVIEW

**Comment by gergnz** [comment]
Awesome, thanks @cmaxwellau. Can you please fix up those rubocop issues, and also can you add some tests and docs? That'd be awesome.  Let me know if you need a hand with anything.

NB. there's a couple of rubocop fixes pending in #239

**Comment by cmaxwellau** [comment]
I've been waiting for the public release, the code was written a month ago :)

I've fixed everything the travis was warning me about, but it's still failing on some code not related to my commit (i think....)
:
lib/cfndsl/external_parameters.rb:56:23: C: Prefer JSON.parse instead of JSON#load.
        params = JSON.load File.read(fname)
                      ^^^^
lib/cfndsl/orchestration_template.rb:79:9: C: Use a guard clause instead of wrapping the code inside a conditional expression.
        unless sname == pname
        ^^^^^^

**Comment by gergnz** [comment]
@cmaxwellau I was reading the docs to write some tests, and it looks like you don't have to supply the hash if you are using AWS::Region for example.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html

```json
{ "Fn::Sub": "/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchConfig --configsets wordpress_install --region ${AWS::Region}" }
```

We should support that too, so we should make the second option optional.

e.g.
```ruby
    # Equivalent to the CloudFormation template built in function Fn::Sub
    def FnSub(string, *substitutions)
      raise 'The first argument passed to Fn::Sub must be a string' unless string.instance_of?(String)
      raise 'Too many arguments to Fn::Sub' if substitutions.length > 1 
      if substitutions[0]      
      raise 'The second argument passed to Fn::Sub must be a Hash' unless substitutions[0].instance_of?(Hash)
            Fn.new('Sub', [string, substitutions[0]])
      else
            Fn.new('Sub', string)
      end
    end
```

Thinking tests might look like:
```ruby
    context 'FnSub', 'String Hash' do
      it 'FnSub String Hash' do
        func = subject.FnSub('foo', 'x' => 'y')
        expect(func.to_json).to eq('{"Fn::Sub":["foo",{"x":"y"}]}')
      end
    end

    context 'FnSub', 'String' do
      it 'FnSub String' do
        func = subject.FnSub('foo')
        expect(func.to_json).to eq('{"Fn::Sub":"foo"}')
      end
    end
```

Thoughts?

**Comment by kornypoet** [comment]
With this, can we also add a deprecation warning to `FnFormat`? It was a cfndsl-only construct and it now seems obsolete.

**Comment by gergnz** [comment]
```patch
diff --git a/lib/cfndsl/jsonable.rb b/lib/cfndsl/jsonable.rb
index 27d89c3..6b67857 100644
--- a/lib/cfndsl/jsonable.rb
+++ b/lib/cfndsl/jsonable.rb
@@ -101,27 +101,7 @@ module CfnDsl
     # TODO Can we simplyfy this somehow?
     # rubocop:disable Metrics/AbcSize, Metrics/PerceivedComplexity, Metrics/CyclomaticComplexity
     def FnFormat(string, *arguments)
-      array = []
-
-      if arguments.empty? || (arguments.length == 1 && arguments[0].instance_of?(Hash))
-        hash = arguments[0] || {}
-        string.scan(/(.*?)(?:%(%|\{([\w:]+)\})|\z)/m) do |x, y, z|
-          array.push x if x && !x.empty?
-
-          next unless y
-
-          array.push(y == '%' ? '%' : (hash[z] || hash[z.to_sym] || Ref(z)))
-        end
-      else
-        string.scan(/(.*?)(?:%(%|\d+)|\z)/m) do |x, y|
-          array.push x if x && !x.empty?
-
-          next unless y
-
-          array.push(y == '%' ? '%' : arguments[y.to_i])
-        end
-      end
-      Fn.new('Join', ['', array])
+      raise 'Fn::Format is no longer supported by CloudFormation. Consider using FnSub'
     end
     # rubocop:enable Metrics/AbcSize, Metrics/PerceivedComplexity, Metrics/CyclomaticComplexity
   end
```

**Comment by cmaxwellau** [comment]
Deprecating FnFormat will break a lot of existing templates. As long as FnJoin is supported, FnFormat will be needed.

**Comment by cmaxwellau** [comment]
@gergnz definitely agree on the optionality for FnSub

**Comment by gergnz** [comment]
@cmaxwellau want to finish this one off, and we can bump a release that includes the new stuff in one go?  We can put FnFormat in a new issue, but is it still supported?  I couldn't find documentation.

**Comment by kornypoet** [comment]
FnFormat is a cfndsl construct only. AWS made FnSub, which obsoletes FnFormat and it should be deprecated. This doesn't mean ripping it out entirely, rather just issue a warning when the method is called that use of this method is discouraged in favor of something new, and its functionality is to be removed at a later time.

**Comment by gergnz** [comment]
thanks for the clarification @kornypoet

**Comment by cmaxwellau** [comment]
@gergnz lets get the initial release in. I think there may be a discrepancy in the doco and need to validate expected vs actual behaviour.

**Comment by kornypoet** [comment]
@cmaxwellau Made a PR against your repo's branch.

**Comment by kornypoet** [comment]
@cmaxwellau Are you good with those adjustments so we can get this merged in?

**Comment by cmaxwellau** [comment]
Sorry for the away time @kornypoet @gergnz  I'm good with the adjustments

**Comment by eric-tucker** [comment]
Quite excited to see this merged in and released with the next gem push.  :+1:

**Comment by razbomi** [comment]
FnSub doesn't entirely supersede FnFormat.  For example, ``` array.push(y == '%' ? '%' : (hash[z] || hash[z.to_sym] || Ref(z)))``` allows for references to be resolved directly in the format string, which made a bit easier to read the code. 

Would this be considered as an enhancement to the FnSub function in the future?

**Pull request closed without merging**
