### PR TITLE
Add yamlllint to Gemfile and add a rake task to lint all yaml files.

### PR DESCRIPTION
**Pull request by gergnz**
Wasn't sure if we should check any other files, but happy to add in the OS types and any of the meta yml files.

### CODE REVIEW

**Comment by stevenjack** [comment]
@gergnz Awesome, let's run all of the yaml files through it.

Could you also add `yamllint` to the default rake task so it's run by travis for each commit.

**Comment by gergnz** [comment]
Pending #192 so that the new yamllint tests can pass.

**Comment by stevenjack** [comment]
@gergnz ready when you are.

**Comment by gergnz** [comment]
@stevenjack passing now.

**Pull request merged**
