### PR TITLE
Fix method missing cop

### PR DESCRIPTION
**Pull request by gergnz**
I'm not totally sure this is the right way to do this, but it's passing rubocop now.

### CODE REVIEW

**Comment by kornypoet** [comment]
You know, I'm actually in favor of just ripping out `#method_missing` entirely. It's usually a code smell when a library uses it anyway. In our particular case, it's only there to provide clarity to dsl methods, but I think Ruby's stacktrace provides enough.

Examples:

```ruby
# sample/t1.rb
CloudFormation do
  description = external_parameters.fetch(:description, 'default description')
  machines = external_parameters.fetch(:machines, 1).to_i

  Description description

  Broke 'stuff'

  (1..machines).each do |i|
    name = "machine#{i}"
    EC2_Instance(name) do
      ImageId 'ami-12345678'
      Type 't1.micro'
    end
  end
end
```

With `#method_missing`:

```
% bundle exec cfndsl -b sample/t1.rb
/Users/trdempsey/dev/ics/cfndsl/sample/t1.rb:7: Undefined symbol: Broke("stuff")
```

Without:

```
% bundle exec cfndsl -b sample/t1.rb
**/Users/trdempsey/dev/ics/cfndsl/sample/t1.rb:7:in `block in eval_file_with_extras': undefined method `Broke' for #<CfnDsl::CloudFormationTemplate:0x007f8189380330> (NoMethodError)
	from /Users/trdempsey/dev/ics/cfndsl/lib/cfndsl/jsonable.rb:173:in `instance_eval'
	from /Users/trdempsey/dev/ics/cfndsl/lib/cfndsl/jsonable.rb:173:in `declare'
	from /Users/trdempsey/dev/ics/cfndsl/lib/cfndsl.rb:94:in `CloudFormation'
	from /Users/trdempsey/dev/ics/cfndsl/sample/t1.rb:1:in `eval_file_with_extras'
	from /Users/trdempsey/dev/ics/cfndsl/lib/cfndsl.rb:88:in `eval'
	from /Users/trdempsey/dev/ics/cfndsl/lib/cfndsl.rb:88:in `eval_file_with_extras'
	from /Users/trdempsey/dev/ics/cfndsl/bin/cfndsl:75:in `<top (required)>'
	from /Users/trdempsey/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/bin/cfndsl:23:in `load'
	from /Users/trdempsey/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/bin/cfndsl:23:in `<main>'**
```

The line in question is still correctly identified, and the scope is now included (`CloudFormationTemplate` in this case). Another thing this will clear up is all of those "Undefined symbol: to_ary" errors when trying to use `puts` inside a template. We could also remove the now unnecessary `#incorrect_capitalization` and `#titleize` methods. Because of [this line](https://github.com/stevenjack/cfndsl/blob/3280f1597d46deed036dab3bc45fdcadc7ab7b34/lib/cfndsl/module.rb#L60) all dsl methods are created with lower and upper case versions anyway, so the "help" offered by [the method missing error](https://github.com/stevenjack/cfndsl/blob/3280f1597d46deed036dab3bc45fdcadc7ab7b34/lib/cfndsl/jsonable.rb#L166) seems moot at this point.

**Comment by cmaxwellau** [comment]
+1 on removing it.

**Comment by gergnz** [comment]
@kornypoet yeah, OK, I'm in favour of that. I'll close my PR, do you want to submit a new one and we'll get those other PRs passing?

**Comment by kornypoet** [comment]
@gergnz I'll have it ready tomorrow.

**Pull request closed without merging**
