### PR TITLE
add support for StepFunctions::StateMachine

### PR DESCRIPTION
**Pull request by simon-weber**
I just added the specs to the top of the files. Let me know if there's some organization I should be following instead.

Also, originally I had updated the entire resource_specification file. But, it looked like then I'd need to define all the new bits, rather than just what I need.

### CODE REVIEW

**Comment by kornypoet** [comment]
@simon-weber Rather than edit the included spec, have you tried updating your local copy with the latest published spec from AWS? If you are using the latest version of `cfndsl` you can run `cfndsl --update-specification`. This should have the resource definition that you need, and cfndsl will load it automatically.

**Comment by simon-weber** [comment]
Ah, that crashes due to https://github.com/stevenjack/cfndsl/pull/345, which I thought meant the yaml change was missing. It looks like that's unrelated, though, so if the other open prs are preferred to this, feel free to close it.

**Comment by kornypoet** [comment]
I see. Temporary workaround would be to manually edit the local resource specification file (it should be `~/.cfndsl/resource_specification.json` and remove the offending section referenced in #345 Hopefully the CloudFormation team moves fast on that.

**Comment by simon-weber** [comment]
Cool. We'll just work around it locally for the time being then. Thanks!

**Pull request closed without merging**
