### PR TITLE
Initial support for Cross stack references

### PR DESCRIPTION
**Pull request by cmaxwellau**
Fix for #242 
#TODO
Add check to Conditions to ensure Fn::Import is not a member of a condition
Rubocop

### CODE REVIEW

**Comment by gergnz** [comment]
Thanks @cmaxwellau, can you fix up the rubocop errors please?

**Comment by cmaxwellau** [comment]
@gergnz Done. Finally got rubocop locally. should be the last time ;)

**Comment by gergnz** [comment]
@cmaxwellau just run bundle and then rake. it does all the tests then.

**Comment by eric-tucker** [comment]
Are you folks bundling up this along with YAML and Fn::Sub for the next release?  Do you have a rough ETA?  Really eager to get to using the stack outputs feature with some generated CFN templates.  :)

**Comment by gergnz** [comment]
@eric-tucker, yes, was just waiting for @cmaxwellau to finish up #244

**Pull request merged**
