### PR TITLE
Add generated changelog

### PR DESCRIPTION
**Pull request by mikechau**
Taking a stab at #299.

Generated a changelog with [github-changelog-generator](https://github.com/skywinder/github-changelog-generator).

Included the gem in case you guys wanted to make it part of your deploy process. But I can remove it if you'd prefer to not include it.

cc: @kidbrax @kornypoet

### CODE REVIEW

**Comment by gergnz** [comment]
@mikechau, nice!

Do you mind bumping the version of ruby to 2.3.3 and check that all the tests pass in travis?

Cheers

**Comment by kidbrax** [comment]
This would be awesome!

**Comment by mikechau** [comment]
Hi @gergnz, looks likes all good!

**Comment by gergnz** [comment]
@mikechau I've added a rake task PR against your branch, if you are happy with that, merge it, and I'll merge this. Nice work.

**Comment by mikechau** [comment]
@gergnz Looks good, the only change I made was I moved the changelog task inside the `bump` task, so we can set the `future_release` option to the new version. This way the change log is generated when you bump the version.

**Pull request merged**
